### ISSUE TITLE
TEST_MOSI_PIN and TEST_MISO_PIN defines don't match when using Yotta

### ISSUE THREAD

**Issue by ernotormikoski** [ARMmbed/example-asynch-spi#15]
In Yotta build (target as frdm-k64f-gcc) TEST_MOSI_PIN and TEST_MISO_PIN defined does not exist in serial_asynch.cpp. Instead there are defines YOTTA_CFG_HARDWARE_TEST_PINS_SPI_MISO and YOTTA_CFG_HARDWARE_TEST_PINS_SPI_MOSI.

After successfully wiring I got correct trace:

Starting short transfer test
Res is 0
Short transfer DONE, event is 4
Starting long transfer test
Res is 0
Long transfer DONE, event is 4
**** Test done ****

**Comment by hasnainvirk** [comment]
Yes. I reproduced it again in OOB2. There is a need to provide information in Readme.md just like example-asynch-serial

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1101

**Comment by 0xc0170** [comment]
I'll fix those Readme soon
